version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo Hello, World!
            echo $CIRCLE_SHA1
    
  deploy_job:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: "Run Deploy Script"
          working_directory: scripts
          command: |
            python3 src/script.py
            poetry --version


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - hold:
          type: approval
      - deploy_job:
          requires:
            - hold
