version: 2.1

jobs:
  
  run_script:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: "Run Deploy Script"
          working_directory: scripts
          command: |
            python3 src/{{ script }}

  test_container:
    parameters:
      image_tag:
        type: string
    docker:
      - image: joeljozarackal/flask_app:<< parameters.image_tag >>
    steps:
      - run:
          name: "Testing Container"
          command: |
            pwd
            hostname
            ls
            ls -a
            ls -la /app

  deploy_integration:
    docker:
      - image: cimg/base:current
    parameters:
      environment_name:
        type: string
      region:
        type: string
    steps:
      - run:
          name: "Running Deployment commands"
          command: |
            echo Deploying application to <<parameters.environment_name>> <<parameters.region>>


            
            


workflows:
  deployment-workflow:
    jobs:
      - run_script
      - test_container:
          name: Test Container
          image_tag: v2
      - deploy_integration:
          name: deploy_integration_to_development_<< matrix.region >>
          environment_name: development
          matrix:
            alias: deploy_integration_development_matrix
            parameters:
              region: {{ regions }}
      - deploy_integration:
          name: deploy_integration_to_production_<< matrix.region >>
          environment_name: production
          matrix:
            alias: deploy_integration_production_matrix
            parameters:
              region: {{ regions }}
          requires:
            - deploy_integration_development_matrix