apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysqlrootpwd: bXlyb290cGFzc3dvcmQ=
  mysqldatabase: aXRlbXNkYg==
  mysql_user: YXBwdXNlcg==
  mysql_password: bXlwYXNzd29yZA==
