apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: joeljozarackal/flask-k8s:v5sqlite
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: https://hacker-news.firebaseio.com/v0/item/8863.json
        # - name: MYSQL_DATABASE
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: mysqldatabase
        # - name: MYSQL_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: mysql_user
        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: mysql_password
        # - name: MYSQL_HOSTNAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: mysql-config
        #       key: mysql_hostname
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100

